import requests

username = input("Введите юзернейм: ").strip()

urls = [
    "https://github.com/",
    "https://www.google.com/",
    "https://www.youtube.com/",
    "https://www.facebook.com/",
    "https://www.reddit.com/",
    "https://www.twitter.com/",
    "https://www.instagram.com/",
    "https://www.linkedin.com/",
    "https://www.tiktok.com/",
    "https://www.netflix.com/",
    "https://www.amazon.com/",
    "https://www.microsoft.com/",
    "https://www.apple.com/",
    "https://www.wikipedia.org/",
    "https://www.stackoverflow.com/",
    "https://www.medium.com/",
    "https://www.pinterest.com/",
    "https://www.paypal.com/",
    "https://www.dropbox.com/",
    "https://www.slack.com/",
    "https://www.tumblr.com/",
    "https://www.quora.com/",
    "https://www.yandex.ru/",
    "https://www.mail.ru/",
    "https://www.ok.ru/",
    "https://www.vk.com/",
    "https://www.zoom.us/",
    "https://www.twitch.tv/",
    "https://www.bing.com/",
    "https://www.adobe.com/",
    "https://www.walmart.com/",
    "https://www.ebay.com/",
    "https://www.aliexpress.com/",
    "https://www.baidu.com/",
    "https://www.office.com/",
    "https://www.whatsapp.com/",
    "https://www.signal.org/",
    "https://www.snapchat.com/",
    "https://www.nytimes.com/",
    "https://www.bbc.com/",
    "https://www.cnn.com/",
    "https://www.nbcnews.com/",
    "https://www.forbes.com/",
    "https://www.bloomberg.com/",
    "https://www.espn.com/",
    "https://www.imdb.com/",
    "https://www.rottentomatoes.com/",
    "https://www.soundcloud.com/",
    "https://www.spotify.com/",
    "https://www.deezer.com/",
    "https://www.shazam.com/",
    "https://www.icloud.com/",
    "https://www.booking.com/",
    "https://www.airbnb.com/",
    "https://www.tripadvisor.com/",
    "https://www.agoda.com/",
    "https://www.kayak.com/",
    "https://www.expedia.com/",
    "https://www.skyscanner.net/",
    "https://www.nike.com/",
    "https://www.adidas.com/",
    "https://www.hm.com/",
    "https://www.zara.com/",
    "https://www.shein.com/",
    "https://www.etsy.com/",
    "https://www.behance.net/",
    "https://www.dribbble.com/",
    "https://www.figma.com/",
    "https://www.canva.com/",
    "https://www.trello.com/",
    "https://www.asana.com/",
    "https://www.notion.so/",
    "https://www.udemy.com/",
    "https://www.coursera.org/",
    "https://www.edx.org/",
    "https://www.khanacademy.org/",
    "https://www.codecademy.com/",
    "https://www.freecodecamp.org/",
    "https://www.w3schools.com/",
    "https://www.geeksforgeeks.org/",
    "https://www.hackerrank.com/",
    "https://www.leetcode.com/",
    "https://www.codeforces.com/",
    "https://www.topcoder.com/",
    "https://www.codewars.com/",
    "https://www.medium.com/",
    "https://www.producthunt.com/",
    "https://www.dev.to/",
    "https://www.digitalocean.com/",
    "https://www.heroku.com/",
    "https://www.vercel.com/",
    "https://www.netlify.com/",
    "https://www.cloudflare.com/",
    "https://www.linode.com/",
    "https://www.aws.amazon.com/",
    "https://www.googlecloudplatform.com/",
    "https://www.azure.microsoft.com/",
    "https://www.docker.com/",
    "https://www.kubernetes.io/",
    "https://www.gitlab.com/",
    "https://www.bitbucket.org/",
    "https://www.npmjs.com/",
    "https://www.pypi.org/",
    "https://www.rubygems.org/",
    "https://www.crates.io/",
    "https://www.nuget.org/",
    "https://www.maven.org/",
    "https://www.packagist.org/",
    "https://www.jenkins.io/",
    "https://www.travis-ci.com/",
    "https://www.circleci.com/",
    "https://www.githubactions.com/",
    "https://www.readthedocs.org/",
    "https://www.python.org/",
    "https://www.rust-lang.org/",
    "https://www.golang.org/",
    "https://www.nodejs.org/",
    "https://www.typescriptlang.org/",
    "https://www.reactjs.org/",
    "https://www.vuejs.org/",
    "https://www.angular.io/",
    "https://www.svelte.dev/",
    "https://www.flutter.dev/",
    "https://www.dart.dev/",
    "https://www.linux.org/",
    "https://www.ubuntu.com/",
    "https://www.debian.org/",
    "https://www.fedora.org/",
    "https://www.kali.org/",
    "https://www.parrotsec.org/",
    "https://www.archlinux.org/",
    "https://www.gentoo.org/",
    "https://www.opensuse.org/",
    "https://www.mozilla.org/",
    "https://www.torproject.org/",
    "https://www.protonmail.com/",
    "https://www.tutanota.com/",
    "https://www.icloud.com/",
    "https://www.megaupload.nz/",
    "https://www.mega.nz/",
    "https://www.mediafire.com/",
    "https://www.zippyshare.com/",
    "https://www.sendspace.com/",
    "https://www.filehippo.com/",
    "https://www.softpedia.com/",
    "https://www.sourceforge.net/",
    "https://www.slackware.com/",
    "https://www.openbsd.org/",
    "https://www.freebsd.org/",
    "https://www.qemu.org/",
    "https://www.virtualbox.org/",
    "https://www.vmware.com/"
]


def check_account(bazo_url, username):
    try:
        url = bazo_url + username
        response = requests.get(url, timeout=1)
        if response.status_code == 200:
            print(f"Акк зареган {url}")
            return True
        elif response.status_code == 404:
            print(f"Акк не найден {url}")
            return False
        else:
            print(f'error: {response.status_code}')
            return False
    except Exception as e:
        print(f'error: {e}')

for url in urls:
    check_account(url, username)
